### ISSUE TITLE
Need to add a license?

### ISSUE THREAD

**Issue by geordiemhall** [YetiTech-Studios/UE4GameLiftClientSDK#2]
Hi there,

Came across this plugin, and seems like a great starting point for GameLift integration :)

One thing that might be good though is to add a License file (or mention the license in the README), since if no license is explicitly specified then someone isn't technically allowed to include your code in their project (since you have the copyright by default).

Were you treating this as something people can freely use, eg. MIT license?
Eg. https://github.com/davevill/UE4-GameLift/blob/master/LICENSE

Thanks!

**Comment by ryanjon2040** [comment]
Hi @geordiemhall I have added a MIT License as requested. :)

https://github.com/YetiTech-Studios/UE4GameLiftClientSDK/blob/master/LICENSE
