### ISSUE TITLE
YetiClient Error Msgs: "aws-cpp-sdk-core" Failed to load

### ISSUE THREAD

**Issue by k2ncore** [YetiTech-Studios/UE4GameLiftClientSDK#20]
After installing YetiTech awsclient plugin those messages appears in launching the project, Play Level and in package the project.. :
1st message : "Failed to load aws-cpp-sdk-core. Plugin will not be functional"
2nd message: "Failed to load aws-cpp-sdk-gamelift."
3rd Message: "Failed to load aws-cpp-sdk-cognito-identity. plugin will not be functional."

I ignored them and continued with the rest of the tutorial. Eventually these cause Packaging to Fail, with following errors:

UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: begin: stack for UAT
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: === Critical error: ===
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error:
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: Fatal error!
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error:
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: Unhandled Exception: 0xc06d007e
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error:
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ffd157ea839 KERNELBASE.dll!UnknownFunction []
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ffc8bb77fbe UE4Editor-AWSCore.dll!__delayLoadHelper2() [d:\agent\_work\2\s\src\vctools\delayimp\delayhlp.cpp:323]
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ffc8bb758b1 UE4Editor-AWSCore.dll!_tailMerge_aws_cpp_sdk_core_dll() []
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ffc8bb73cbf UE4Editor-AWSCore.dll!FAWSCoreModule::ShutdownModule() [d:\projects\nectar\plugins\gameliftclientsdk\source\awscore\private\awscoremodule.cpp:40]
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ffcb4be61e7 UE4Editor-Core.dll!FModuleManager::UnloadModulesAtShutdown() [d:\unrealengine-release\engine\source\runtime\core\private\modules\modulemanager.cpp:730]
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ff70beb4be0 UE4Editor-Cmd.exe!FEngineLoop::Exit() [d:\unrealengine-release\engine\source\runtime\launch\private\launchengineloop.cpp:3483]
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ff70beb5581 UE4Editor-Cmd.exe!GuardedMain() [d:\unrealengine-release\engine\source\runtime\launch\private\launch.cpp:179]
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ff70beb55ca UE4Editor-Cmd.exe!GuardedMainWrapper() [d:\unrealengine-release\engine\source\runtime\launch\private\windows\launchwindows.cpp:145]
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ff70bec316c UE4Editor-Cmd.exe!WinMain() [d:\unrealengine-release\engine\source\runtime\launch\private\windows\launchwindows.cpp:275]
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ff70bec4cb6 UE4Editor-Cmd.exe!__scrt_common_main_seh() [d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ffd168b7bd4 KERNEL32.DLL!UnknownFunction []
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: [Callstack] 0x00007ffd17d8ce71 ntdll.dll!UnknownFunction []
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error:
UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: end: stack for UAT
UATHelper: Packaging (Windows (64-bit)): Took 563.7799446s to run UE4Editor-Cmd.exe, ExitCode=-1073741819
UATHelper: Packaging (Windows (64-bit)): ERROR: Cook failed.

Am I making some mistake?
I also read the part where you mentioned that the dll have been recently modified and you will be working on the same. Just thought you might want to know this as well.

**Comment by chris-gong** [comment]
For now, please use the older version of the SDK that can be found here, 688cc418cc3b7fe8e0eaae5aefbb3758ddc89120, until I can fix this issue.

**Comment by k2ncore** [comment]
Any idea on if I want to make Android Build from this?

**Comment by k2ncore** [comment]
Got the PC build to work. Much Thanks.
