### ISSUE TITLE
aws-cpp core and gamelift DLLs not loading on packaged game

### ISSUE THREAD

**Issue by maucoen** [YetiTech-Studios/UE4GameLiftClientSDK#4]
Hi all,

There may be a problem with the paths for packaged game dlls, as my gameliftclient plugin crashes the exe when I run a packaged version (editor version and standalone are working). Any pointers as to where the error might be? The dlls are in the packaged game plugin folder, but I have yet to check the paths for them in the plugin.

**Comment by ryanjon2040** [comment]
I was able to fix the issue partially but the changes I made is causing AWSCore.dll to fail. Right now the workaround is to place all the dll files right next to the Game exe (i.e: **_YourGameName\Binaries\Win64_** location).

**Comment by maucoen** [comment]
workaround is good for now!

**Comment by ryanjon2040** [comment]
@maucoen This issue has been resolved in this commit 83b49230e2f79d1ee487bd55cc16edbf4bf8a025

**Comment by maucoen** [comment]
pulled the commit and it works, thanks!
