### ISSUE TITLE
LogGameLiftClient: Error: [UGameLiftDescribeGameSession::OnDescribeGameSessionState] Received OnDescribeGameSessionState with failed outcome. Error: Unable to parse ExceptionName: ApiNotSupportedException Message: API GameLift.DescribeGameSessionDetails is not recognized by GameLift Local.

### ISSUE THREAD

**Issue by AngerDark** [YetiTech-Studios/UE4GameLiftClientSDK#8]
Hi guys, im testing my client and server with gamelift.
Followed your guide to integrate it in my client.

I've configured gamelift for local testing using gamelift local
(https://docs.aws.amazon.com/gamelift/latest/developerguide/integration-testing-local.html)
But when i call DescribeSession node from blueprint i get an error:
LogGameLiftClient: Error: [UGameLiftDescribeGameSession::OnDescribeGameSessionState] Received OnDescribeGameSessionState with failed outcome. Error: Unable to parse ExceptionName: ApiNotSupportedException Message: API GameLift.DescribeGameSessionDetails is not recognized by GameLift Local.

Here is Gamelift Local Console output
![default](https://user-images.githubusercontent.com/5540467/39282554-035b0af8-4934-11e8-8524-1bbf2e5557cf.png)

**Comment by chiefGui** [comment]
After checking https://github.com/YetiTech-Studios/UE4GameLiftClientSDK/blob/1f2ce3bd3af7b9abf14e6bb747557b39b32dc20e/GameLiftClientSDK/Source/GameLiftClientSDK/Private/GameLiftClientApi.cpp#L159, the problem is most likely on your `GameSessionId`.

Are you sure your GameSessionId is correct?

**Comment by chiefGui** [comment]
Nah, pardon me, bad information above.

Seems like this is an error on the plug-in itself. If you have C++ knowledge, place a pull request, otherwise let's wait for the author @ryanjon2040 to give us a feedback on how to proceed with this.

**Comment by SyedAman** [comment]
I think `OnDescribeGameSessionState` is not supported in AWS Gamelift Local

**Comment by ryanjon2040** [comment]
Sorry for the delayed response. 

Certain API calls are not supported by GameLift plugin. This is a limitation from Amazon itself and not a bug.

**Comment by ryanjon2040** [comment]
@SyedAman Yes they are not supported by GameLift Local but they work in actual Gamelift service.
